In [1]:
import numpy as np

In [5]:
#--3.1 1D Numpy Arrays--
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list)

print(4*arr)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
min_index = np.argmin(arr)
max_index = np.argmax(arr)
print(f'max value: {arr[max_index]}, min value: {arr[min_index]}')
print(f'max value: {np.max(arr)}, min value: {np.min(arr)}')
arr2 = arr > 20
print(arr2)

[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
max value: 50, min value: 4
max value: 50, min value: 4
[False  True False False  True False False  True  True  True]


In [22]:
#--3.2 2D Numpy Arrays--
matrix = np.array([
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
])
print(np.shape(matrix))
print(matrix[:,2])
print(matrix[1,:])
double_matrix = matrix * 2
print(double_matrix)
mean_column = np.mean(matrix, axis=0)
print(mean_column)
mean_matrix = np.mean(matrix)
print(mean_matrix)
print(np.max(matrix, axis=1), np.min(matrix, axis=0))
matrix_flatten = matrix.flatten()
print(matrix_flatten) #flatten turned the 2D array into a 1D array, matrix to vector
flat_min_index = np.argmin(matrix_flatten)
flat_max_index = np.argmax(matrix_flatten)
min_coord = np.unravel_index(flat_min_index, (3,4))
max_coord = np.unravel_index(flat_max_index, (3,4))
print(min_coord, max_coord)
matrix_greater15 = matrix > 15
sorted_matrix = np.sort(matrix, axis = 1)
print(sorted_matrix)

(3, 4)
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
[ 6.33333333 15.33333333 16.66666667  7.66666667]
11.5
[17 21 19] [ 5 12 14  3]
[ 5 12 17  9  8 21 14  3  6 13 19 11]
(np.int64(1), np.int64(3)) (np.int64(1), np.int64(1))
[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [ ]:
print("dick and balls")